### ISSUE TITLE
Riak CS doesn't start due to an apparent path 

### ISSUE THREAD

**Issue by Bob-The-Marauder** [TI-Tokyo/riak_cs#1]
https://github.com/TI-Tokyo/riak_cs/blob/3.0.0rc2/rel/files/riak-cs#L57 has `$PID_DIR/riak-cs.pid`. `$PID_DIR` includes a trailing slash which causes 

```
Nov 16 13:37:40 buster riak-cs[12122]: /usr/sbin/riak-cs: line 57: /run/riak-cs//riak-cs.pid: Permission denied
```

substituting `${PID_DIR}riak-cs.pid` seems to fix the issue.

We also found that /var/lib/riak-cs/vm.args and /var/lib/riak-cs/sys.config had permissions issues that stopped Riak CS from starting. These were remedied by changing the owner to Riak CS initially and later changing the permissions to 777. This, of course, consitutes a security flaw, so a better solution needs to be found.

For reference:
```
root@buster:/var/lib/riak-cs# systemctl status riak-cs
● riak-cs.service - Riak CS Database
   Loaded: loaded (/lib/systemd/system/riak-cs.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2021-11-16 08:55:26 GMT; 4h 16min ago
  Process: 10332 ExecStart=/usr/sbin/riak-cs start (code=exited, status=0/SUCCESS)
  Process: 10640 ExecStop=/usr/sbin/riak-cs stop (code=exited, status=0/SUCCESS)
 Main PID: 10332 (code=exited, status=0/SUCCESS)

Nov 16 08:55:19 buster systemd[1]: Starting Riak CS Database...
Nov 16 08:55:19 buster systemd[1]: Started Riak CS Database.
Nov 16 08:55:19 buster riak-cs[10332]: /usr/sbin/riak-cs: line 41: /var/lib/riak-cs/sys.config: Permission denied
Nov 16 08:55:19 buster riak-cs[10332]: /usr/sbin/riak-cs: line 46: /var/lib/riak-cs/vm.args: Permission denied
Nov 16 08:55:22 buster riak-cs[10332]: /usr/sbin/riak-cs: line 57: /run/riak-cs//riak-cs.pid: Permission denied
Nov 16 08:55:22 buster riak-cs[10640]: /usr/sbin/riak-cs: line 41: /var/lib/riak-cs/sys.config: Permission denied
Nov 16 08:55:22 buster riak-cs[10640]: /usr/sbin/riak-cs: line 46: /var/lib/riak-cs/vm.args: Permission denied
Nov 16 08:55:23 buster riak-cs[10640]: ok
Nov 16 08:55:26 buster systemd[1]: riak-cs.service: Succeeded.
```

**Comment by hmmr** [comment]
Please review https://github.com/TI-Tokyo/riak_cs/pull/2, with changes to address this issue (also https://github.com/TI-Tokyo/stanchion/pull/1, with a similar set of changes in stanchion).

I have tested both changesets on debian11 and centos8, and confirmed that:
* packages can be built and installed;
* both riak-cs and stanchion can be started, and behave identically, via `riak-cs start` as well as `systemctl start riak-cs` (same for stanchion), except that when started as `riak-cs start`, it is untracked by systemd (`systemctl` does not see or stop it). Whichever way it is started, `riak-cs ping`, `riak-cs-admin status` work as expected.

I was not able to able to deal with (or squelch) this warning:
```
systemd[1]: riak-cs.service: Supervising process 12736 which is not our child. We'll most likely not notice when it exits.
```
which appears to be harmless.

**Comment by hmmr** [comment]
With #2 merged, closing.
