### ISSUE TITLE
Building from clean repository

### ISSUE THREAD

**Issue by ThomasArts** [TI-Tokyo/riak_cs#8]
I get a lot of errors due to wrong versions of dependencies when building a clean repository from scratch.

This is how you can reproduce it:
- MacOS (but that's not the problem) with Erlang OTP 24

`git clone https://github.com/TI-Tokyo/riak_cs`
`cd riak_cs`
`git checkout 3.0.1`
`./rebar3 compile`

As an example:
```
===> Compiling _build/default/plugins/cuttlefish/src/cuttlefish_util.erl failed
_build/default/plugins/cuttlefish/src/cuttlefish_util.erl:none: error in parse transform 'lager_transform':
exception error: bad argument
  in function  integer_to_list/1
     called as integer_to_list({46,5})
     *** argument 1: not an integer
```     
This is due to the fact that old versions of parse transform use only lines in the abstract forms, later versions have line and column. There are newer versions available, but the dependencies must be updated.

**Comment by Bob-The-Marauder** [comment]
I have confirmed this issue internally. We'll look at updating the dependencies and issuing a new tag once fixed.

For the moment, it builds successfully with OTP 22.3 on Mac OS when I execute the following:

```
git clone https://github.com/TI-Tokyo/riak_cs
cd riak_cs
git checkout tags/3.0.1
make rel
```

If relevant, I built OTP 22.3 using kerl.
